version: "3.7"
services:
  app:
    container_name: container-node
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    volumes:
      - ./:/app
  mongo:
    container_name: mongo
    image: mongo
    ports: ["27017:27017"]